spring:
  application:
    name: app-translator
  profiles:
    active: dev
server:
  port: 80

telegram:
  webhook-path: "YOUR_BOT_WEBHOOK"
  bot-name: "YOUR_BOT_USERNAME"
  bot-token: "YOUR_BOT_TOKEN"
  chat-id:
    log: YOUR_LOGGING_CHAT_ID

app:
  google:
    cloud:
      project-id: YOUR_CLOUD_PROJECT_ID

logging:
  level:
    root: warn
  file:
    name: app-pdf-bot.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"